<?php

namespace ContainerSiPYR1G;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CFivKQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CFivK_Q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CFivK_Q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'menu' => ['privates', '.errored..service_locator.CFivK_Q.App\\Entity\\Menu', NULL, 'Cannot autowire service ".service_locator.CFivK_Q": it references class "App\\Entity\\Menu" but no such service exists.'],
        ], [
            'menu' => 'App\\Entity\\Menu',
        ]);
    }
}
