<?php

namespace ContainerSiPYR1G;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FkYDLxPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fkYDLxP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fkYDLxP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'contactRepository' => ['privates', 'App\\Repository\\ContactRepository', 'getContactRepositoryService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'reservationsRepository' => ['privates', 'App\\Repository\\ReservationsRepository', 'getReservationsRepositoryService', true],
        ], [
            'contactRepository' => 'App\\Repository\\ContactRepository',
            'mailer' => '?',
            'reservationsRepository' => 'App\\Repository\\ReservationsRepository',
        ]);
    }
}
