<?php

namespace ContainerSiPYR1G;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QGmoEnmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qGmoEnm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qGmoEnm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'admin' => ['privates', '.errored..service_locator.qGmoEnm.App\\Entity\\Admin', NULL, 'Cannot autowire service ".service_locator.qGmoEnm": it references class "App\\Entity\\Admin" but no such service exists.'],
            'adminRepository' => ['privates', 'App\\Repository\\AdminRepository', 'getAdminRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userPasswordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'admin' => 'App\\Entity\\Admin',
            'adminRepository' => 'App\\Repository\\AdminRepository',
            'entityManager' => '?',
            'userPasswordHasher' => '?',
        ]);
    }
}
