<?php

namespace ContainerSiPYR1G;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NhqcWpRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NhqcWpR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NhqcWpR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'menuRepository' => ['privates', 'App\\Repository\\MenuRepository', 'getMenuRepositoryService', true],
            'metRepository' => ['privates', 'App\\Repository\\MetRepository', 'getMetRepositoryService', true],
            'pdfService' => ['privates', 'App\\Services\\PdfService', 'getPdfServiceService', true],
        ], [
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'menuRepository' => 'App\\Repository\\MenuRepository',
            'metRepository' => 'App\\Repository\\MetRepository',
            'pdfService' => 'App\\Services\\PdfService',
        ]);
    }
}
