<?php

namespace ContainerFcPIxvR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y2CpsMLService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Y2CpsML' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Y2CpsML'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'mailerService' => ['privates', 'App\\Services\\MailerService', 'getMailerServiceService', true],
            'reservation' => ['privates', '.errored..service_locator.Y2CpsML.App\\Entity\\Reservations', NULL, 'Cannot autowire service ".service_locator.Y2CpsML": it references class "App\\Entity\\Reservations" but no such service exists.'],
            'reservationsRepository' => ['privates', 'App\\Repository\\ReservationsRepository', 'getReservationsRepositoryService', true],
            'statusRepository' => ['privates', 'App\\Repository\\StatusRepository', 'getStatusRepositoryService', true],
        ], [
            'mailer' => '?',
            'mailerService' => 'App\\Services\\MailerService',
            'reservation' => 'App\\Entity\\Reservations',
            'reservationsRepository' => 'App\\Repository\\ReservationsRepository',
            'statusRepository' => 'App\\Repository\\StatusRepository',
        ]);
    }
}
