<?php

namespace ContainerFcPIxvR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z8RKYyLService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Z8RKYyL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Z8RKYyL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'met' => ['privates', '.errored..service_locator.Z8RKYyL.App\\Entity\\Met', NULL, 'Cannot autowire service ".service_locator.Z8RKYyL": it references class "App\\Entity\\Met" but no such service exists.'],
        ], [
            'met' => 'App\\Entity\\Met',
        ]);
    }
}
