<?php

namespace ContainerFcPIxvR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3I9xZsHService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.3I9xZsH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3I9xZsH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mailerService' => ['privates', 'App\\Services\\MailerService', 'getMailerServiceService', true],
            'reservationsRepository' => ['privates', 'App\\Repository\\ReservationsRepository', 'getReservationsRepositoryService', true],
            'statusRepository' => ['privates', 'App\\Repository\\StatusRepository', 'getStatusRepositoryService', true],
        ], [
            'mailerService' => 'App\\Services\\MailerService',
            'reservationsRepository' => 'App\\Repository\\ReservationsRepository',
            'statusRepository' => 'App\\Repository\\StatusRepository',
        ]);
    }
}
