<?php

namespace ContainerFcPIxvR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VNkOBdgService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.VNkOBdg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VNkOBdg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'mailerService' => ['privates', 'App\\Services\\MailerService', 'getMailerServiceService', true],
        ], [
            'entityManager' => '?',
            'mailerService' => 'App\\Services\\MailerService',
        ]);
    }
}
