<?php

namespace ContainerFcPIxvR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O5DY0xRService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.o5DY0xR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.o5DY0xR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'menuRepository' => ['privates', 'App\\Repository\\MenuRepository', 'getMenuRepositoryService', true],
            'met' => ['privates', '.errored..service_locator.o5DY0xR.App\\Entity\\Met', NULL, 'Cannot autowire service ".service_locator.o5DY0xR": it references class "App\\Entity\\Met" but no such service exists.'],
            'metRepository' => ['privates', 'App\\Repository\\MetRepository', 'getMetRepositoryService', true],
        ], [
            'entityManager' => '?',
            'menuRepository' => 'App\\Repository\\MenuRepository',
            'met' => 'App\\Entity\\Met',
            'metRepository' => 'App\\Repository\\MetRepository',
        ]);
    }
}
