<?php

namespace ContainerFcPIxvR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFlatpickrDateTimeTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\Extension\FlatpickrDateTimeType' shared autowired service.
     *
     * @return \App\Form\Extension\FlatpickrDateTimeType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\Extension\\FlatpickrDateTimeType'] = new \App\Form\Extension\FlatpickrDateTimeType();
    }
}
