<?php

namespace ContainerFcPIxvR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMenu2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.CrUZbNp.App\Entity\Menu' shared service.
     *
     * @return \App\Entity\Menu
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.CrUZbNp": it references class "App\\Entity\\Menu" but no such service exists.');
    }
}
