<?php

namespace ContainerFcPIxvR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMetRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\MetRepository' shared autowired service.
     *
     * @return \App\Repository\MetRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\MetRepository'] = new \App\Repository\MetRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
