<?php

namespace ContainerFcPIxvR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMet3Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.pN7drrT.App\Entity\Met' shared service.
     *
     * @return \App\Entity\Met
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.pN7drrT": it references class "App\\Entity\\Met" but no such service exists.');
    }
}
