<?php

namespace ContainerFcPIxvR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMetTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\MetType' shared autowired service.
     *
     * @return \App\Form\MetType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\MetType'] = new \App\Form\MetType();
    }
}
