<?php

namespace ContainerFcPIxvR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPdfServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Services\PdfService' shared autowired service.
     *
     * @return \App\Services\PdfService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Services\\PdfService'] = new \App\Services\PdfService();
    }
}
