<?php

namespace ContainerFcPIxvR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationsTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ReservationsType' shared autowired service.
     *
     * @return \App\Form\ReservationsType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ReservationsType'] = new \App\Form\ReservationsType();
    }
}
