<?php

namespace ContainerFcPIxvR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationsRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ReservationsRepository' shared autowired service.
     *
     * @return \App\Repository\ReservationsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ReservationsRepository'] = new \App\Repository\ReservationsRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
