<?php

namespace ContainerWOhZZ56;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PN7drrTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pN7drrT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pN7drrT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'met' => ['privates', '.errored..service_locator.pN7drrT.App\\Entity\\Met', NULL, 'Cannot autowire service ".service_locator.pN7drrT": it references class "App\\Entity\\Met" but no such service exists.'],
            'metRepository' => ['privates', 'App\\Repository\\MetRepository', 'getMetRepositoryService', true],
        ], [
            'met' => 'App\\Entity\\Met',
            'metRepository' => 'App\\Repository\\MetRepository',
        ]);
    }
}
