<?php

namespace ContainerWOhZZ56;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EEJdgugService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EEJdgug' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EEJdgug'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reservation' => ['privates', '.errored..service_locator.EEJdgug.App\\Entity\\Reservations', NULL, 'Cannot autowire service ".service_locator.EEJdgug": it references class "App\\Entity\\Reservations" but no such service exists.'],
            'reservationsRepository' => ['privates', 'App\\Repository\\ReservationsRepository', 'getReservationsRepositoryService', true],
            'statusRepository' => ['privates', 'App\\Repository\\StatusRepository', 'getStatusRepositoryService', true],
        ], [
            'reservation' => 'App\\Entity\\Reservations',
            'reservationsRepository' => 'App\\Repository\\ReservationsRepository',
            'statusRepository' => 'App\\Repository\\StatusRepository',
        ]);
    }
}
