<?php

namespace ContainerWOhZZ56;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFlatpickrDateTimeTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Extension\FlatpickrDateTimeType' shared autowired service.
     *
     * @return \App\Form\Extension\FlatpickrDateTimeType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Extension/FlatpickrDateTimeType.php';

        return $container->privates['App\\Form\\Extension\\FlatpickrDateTimeType'] = new \App\Form\Extension\FlatpickrDateTimeType();
    }
}
