<?php

namespace ContainerWOhZZ56;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMenuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.CFivK_Q.App\Entity\Menu' shared service.
     *
     * @return \App\Entity\Menu
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.CFivK_Q": it references class "App\\Entity\\Menu" but no such service exists.');
    }
}
