<?php

namespace ContainerWOhZZ56;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPdfServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\PdfService' shared autowired service.
     *
     * @return \App\Services\PdfService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/PdfService.php';

        return $container->privates['App\\Services\\PdfService'] = new \App\Services\PdfService();
    }
}
