<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSiPYR1G\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSiPYR1G/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSiPYR1G.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSiPYR1G\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSiPYR1G\App_KernelDevDebugContainer([
    'container.build_hash' => 'SiPYR1G',
    'container.build_id' => '4cda5c38',
    'container.build_time' => 1667604430,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSiPYR1G');
